# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_auto_20151231_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='result',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sport.Result'),
        ),
        # migrations.AlterField(
        #     model_name='result',
        #     name='score',
        #     field=models.IntegerField(blank=True, default=0),
        # ),
    ]
