# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0005_auto_20151231_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='result',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sport.Result'),
        ),
    ]
