# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0006_auto_20151231_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='result',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
