# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0007_auto_20151231_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='place',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
