# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0008_auto_20151231_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='numberOfParticipants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='personalNotes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
