# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0009_auto_20151231_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='result',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
